from OpenCV_imread import imreadUnicode


# 찾을 이미지
우마무스메_실행 = imreadUnicode(r"./Images/우마무스메_실행.png")
게스트_로그인 = imreadUnicode(r"./Images/게스트_로그인.png")
게스트로_로그인_하시겠습니까 = imreadUnicode(r"./Images/게스트로_로그인_하시겠습니까.png")
전체_동의 = imreadUnicode(r"./Images/전체_동의.png")
시작하기 = imreadUnicode(r"./Images/시작하기.png")
TAP_TO_START = imreadUnicode(r"./Images/TAP_TO_START.png")
계정_연동_설정_요청 = imreadUnicode(r"./Images/계정_연동_설정_요청.png")
게임_데이터_다운로드 = imreadUnicode(r"./Images/게임_데이터_다운로드.png")
SKIP = imreadUnicode(r"./Images/SKIP.png")
출전 = imreadUnicode(r"./Images/출전.png")
울려라_팡파레 = imreadUnicode(r"./Images/울려라_팡파레.png")
닿아라_골까지 = imreadUnicode(r"./Images/닿아라_골까지.png")
라이브_메뉴 = imreadUnicode(r"./Images/라이브_메뉴.png")
라이브_스킵 = imreadUnicode(r"./Images/라이브_스킵.png")
타즈나_씨와_레이스를_관전한 = imreadUnicode(r"./Images/타즈나_씨와_레이스를_관전한.png")
일본_우마무스메_트레이닝_센터_학원 = imreadUnicode(r"./Images/일본_우마무스메_트레이닝_센터_학원.png")
레이스의_세계를_꿈꾸는_아이들이 = imreadUnicode(r"./Images/레이스의_세계를_꿈꾸는_아이들이.png")
환영 = imreadUnicode(r"./Images/환영.png")
느낌표물음표 = imreadUnicode(r"./Images/느낌표물음표.png")
아키카와_이사장님 = imreadUnicode(r"./Images/아키카와_이사장님.png")
장래_유망한_트레이너의_등장에 = imreadUnicode(r"./Images/장래_유망한_트레이너의_등장에.png")
나는_이_학원의_이사장 = imreadUnicode(r"./Images/나는_이_학원의_이사장.png")
자네에_대해_가르쳐_주게나 = imreadUnicode(r"./Images/자네에_대해_가르쳐_주게나.png")
트레이너_정보를_입력해주세요 = imreadUnicode(r"./Images/트레이너_정보를_입력해주세요.png")
등록한다 = imreadUnicode(r"./Images/등록한다.png")
이_내용으로_등록합니다_등록하시겠습니까 = imreadUnicode(r"./Images/이_내용으로_등록합니다_등록하시겠습니까.png")
자네는_트레센_학원의_일원일세 = imreadUnicode(r"./Images/자네는_트레센_학원의_일원일세.png")
담당_우마무스메와_함께 = imreadUnicode(r"./Images/담당_우마무스메와_함께.png")
학원에_다니는_우마무스메의 = imreadUnicode(r"./Images/학원에_다니는_우마무스메의.png")
자네는_트레이너로서_담당_우마무스메를 = imreadUnicode(r"./Images/자네는_트레이너로서_담당_우마무스메를.png")
가슴에_단_트레이너_배지에 = imreadUnicode(r"./Images/가슴에_단_트레이너_배지에.png")
실전_연수를_하러_가시죠 = imreadUnicode(r"./Images/실전_연수를_하러_가시죠.png")
프리티_더비_뽑기_5번_뽑기_무료 = imreadUnicode(r"./Images/프리티_더비_뽑기_5번_뽑기_무료.png")
튜토리얼_용_프리티_더비_뽑기 = imreadUnicode(r"./Images/튜토리얼_용_프리티_더비_뽑기.png")
서포트_카드_화살표 = imreadUnicode(r"./Images/서포트_카드_화살표.png")
서포트_카드_화살표2 = imreadUnicode(r"./Images/서포트_카드_화살표2.png")
서포트_카드_뽑기_10번_뽑기_무료 = imreadUnicode(r"./Images/서포트_카드_뽑기_10번_뽑기_무료.png")
튜토리얼_용_서포트_카드_뽑기 = imreadUnicode(r"./Images/튜토리얼_용_서포트_카드_뽑기.png")
육성_화살표 = imreadUnicode(r"./Images/육성_화살표.png")
육성_시나리오를_공략하자 = imreadUnicode(r"./Images/육성_시나리오를_공략하자.png")
다음_화살표 = imreadUnicode(r"./Images/다음_화살표.png")
트윙클_시리즈에_도전_우마무스메의_꿈을_이뤄주자 = imreadUnicode(r"./Images/트윙클_시리즈에_도전_우마무스메의_꿈을_이뤄주자.png")
마음에_드는_우마무스메를_육성하자 = imreadUnicode(r"./Images/마음에_드는_우마무스메를_육성하자.png")
다이와_스칼렛_클릭 = imreadUnicode(r"./Images/다이와_스칼렛_클릭.png")
다음_화살표_육성_우마무스메_선택 = imreadUnicode(r"./Images/다음_화살표_육성_우마무스메_선택.png")
플러스_계승_우마무스메_선택_화살표 = imreadUnicode(r"./Images/플러스_계승_우마무스메_선택_화살표.png")
계승_보드카_선택_화살표 = imreadUnicode(r"./Images/계승_보드카_선택_화살표.png")
보드카_결정_화살표 = imreadUnicode(r"./Images/보드카_결정_화살표.png")
자동_선택_화살표 = imreadUnicode(r"./Images/자동_선택_화살표.png")
자동_선택_확인_OK_화살표 = imreadUnicode(r"./Images/자동_선택_확인_OK_화살표.png")
마음을_이어서_꿈을_이루자 = imreadUnicode(r"./Images/마음을_이어서_꿈을_이루자.png")
계승_최종_다음_화살표 = imreadUnicode(r"./Images/계승_최종_다음_화살표.png")
서포트_카드를_편성해서_육성_효율_UP = imreadUnicode(r"./Images/서포트_카드를_편성해서_육성_효율_UP.png")
서포트_카드의_타입에_주목 = imreadUnicode(r"./Images/서포트_카드의_타입에_주목.png")
우정_트레이닝이_육성의_열쇠를_쥐고_있다 = imreadUnicode(r"./Images/우정_트레이닝이_육성의_열쇠를_쥐고_있다.png")
서포트_자동_편성_화살표 = imreadUnicode(r"./Images/서포트_자동_편성_화살표.png")
육성_시작_화살표 = imreadUnicode(r"./Images/육성_시작_화살표.png")
TP를_소비해_육성_시작_화살표 = imreadUnicode(r"./Images/TP를_소비해_육성_시작_화살표.png")
초록색_역삼각형 = imreadUnicode(r"./Images/초록색_역삼각형.png")
TAP = imreadUnicode(r"./Images/TAP.png")
우마무스메에겐_저마다_다른_목표가_있습니다 = imreadUnicode(r"./Images/우마무스메에겐_저마다_다른_목표가_있습니다.png")
이쪽은_육성을_진행할_때_필요한_커맨드입니다 = imreadUnicode(r"./Images/이쪽은_육성을_진행할_때_필요한_커맨드입니다.png")
커맨드를_하나_실행하면_턴을_소비합니다 = imreadUnicode(r"./Images/커맨드를_하나_실행하면_턴을_소비합니다.png")
우선_트레이닝을_선택해_보세요 = imreadUnicode(r"./Images/우선_트레이닝을_선택해_보세요.png")
이게_실행할_수_있는_트레이닝들입니다 = imreadUnicode(r"./Images/이게_실행할_수_있는_트레이닝들입니다.png")
한_번_스피드를_골라_보세요 = imreadUnicode(r"./Images/한_번_스피드를_골라_보세요.png")
파란색_역삼각형 = imreadUnicode(r"./Images/파란색_역삼각형.png")
약속 = imreadUnicode(r"./Images/약속.png")
서둘러_가봐 = imreadUnicode(r"./Images/서둘러_가봐.png")
그때_번뜩였다 = imreadUnicode(r"./Images/그때_번뜩였다.png")
다이와_스칼렛의_성장으로_이어졌다 = imreadUnicode(r"./Images/다이와_스칼렛의_성장으로_이어졌다.png")
다음으로_육성_우마무스메의_체력에_관해_설명할게요 = imreadUnicode(r"./Images/다음으로_육성_우마무스메의_체력에_관해_설명할게요.png")
우선_아까처럼_트레이닝을_선택해_보세요 = imreadUnicode(r"./Images/우선_아까처럼_트레이닝을_선택해_보세요.png")
여기_실패율에_주목해_주세요 = imreadUnicode(r"./Images/여기_실패율에_주목해_주세요.png")
남은_체력이_적을수록_실패율이_높아지게_돼요 = imreadUnicode(r"./Images/남은_체력이_적을수록_실패율이_높아지게_돼요.png")
트레이닝에_실패하면_능력과_컨디션이 = imreadUnicode(r"./Images/트레이닝에_실패하면_능력과_컨디션이.png")
돌아간다_화살표 = imreadUnicode(r"./Images/돌아간다_화살표.png")
체력이_적을_때는_우마무스메를 = imreadUnicode(r"./Images/체력이_적을_때는_우마무스메를.png")
먼저_여기_스킬을_선택해보세요 = imreadUnicode(r"./Images/먼저_여기_스킬을_선택해보세요.png")
다음으로_배울_스킬을_선택하세요 = imreadUnicode(r"./Images/다음으로_배울_스킬을_선택하세요.png")
이번에는_이_스킬을_습득해_보세요 = imreadUnicode(r"./Images/이번에는_이_스킬을_습득해_보세요.png")
스킬_결정_화살표 = imreadUnicode(r"./Images/스킬_결정_화살표.png")
스킬_획득_화살표 = imreadUnicode(r"./Images/스킬_획득_화살표.png")
스킬_획득_돌아간다_화살표 = imreadUnicode(r"./Images/스킬_획득_돌아간다_화살표.png")
이졔_준비가_다_끝났어요_레이스에_출전해_봐요 = imreadUnicode(r"./Images/이졔_준비가_다_끝났어요_레이스에_출전해_봐요.png")
출전_화살표 = imreadUnicode(r"./Images/출전_화살표.png")
숫자1등이_되기_위해서도_말야 = imreadUnicode(r"./Images/숫자1등이_되기_위해서도_말야.png")
패덕에서는_레이스에_출전하는_우마무스메의 = imreadUnicode(r"./Images/패덕에서는_레이스에_출전하는_우마무스메의.png")
우선_예상_표시에_관해서_설명할게요 = imreadUnicode(r"./Images/우선_예상_표시에_관해서_설명할게요.png")
숫자3개의_표시는_전문가들의_예상을_나타내며 = imreadUnicode(r"./Images/숫자3개의_표시는_전문가들의_예상을_나타내며.png")
능력과_컨디션이_좋을수록_많은_기대를_받게_돼서 = imreadUnicode(r"./Images/능력과_컨디션이_좋을수록_많은_기대를_받게_돼서.png")
물론_반드시_우승하게_되는_건_아니지만 = imreadUnicode(r"./Images/물론_반드시_우승하게_되는_건_아니지만.png")
또_패덕에서는_우마무스메의_작전을 = imreadUnicode(r"./Images/또_패덕에서는_우마무스메의_작전을.png")
선행A_화살표 = imreadUnicode(r"./Images/선행A_화살표.png")
작전_결정 = imreadUnicode(r"./Images/작전_결정.png")
이것으로_준비는_다_됐어요 = imreadUnicode(r"./Images/이것으로_준비는_다_됐어요.png")
첫_우승_축하_드려요 = imreadUnicode(r"./Images/첫_우승_축하_드려요.png")
좋아 = imreadUnicode(r"./Images/좋아.png")
목표_달성 = imreadUnicode(r"./Images/목표_달성.png")
육성_목표_달성 = imreadUnicode(r"./Images/육성_목표_달성.png")
육성_수고하셨습니다 = imreadUnicode(r"./Images/육성_수고하셨습니다.png")
스킬_포인트가_남았다면 = imreadUnicode(r"./Images/스킬_포인트가_남았다면.png")
육성은_이것으로_종료입니다 = imreadUnicode(r"./Images/육성은_이것으로_종료입니다.png")
또_연수_기간은_짧았지만 = imreadUnicode(r"./Images/또_연수_기간은_짧았지만.png")
육성_완료_화살표 = imreadUnicode(r"./Images/육성_완료_화살표.png")
육성_완료_확인_완료한다_화살표 = imreadUnicode(r"./Images/육성_완료_확인_완료한다_화살표.png")
육성을_끝낸_우마무스메는_일정_기준으로_평가받은_후 = imreadUnicode(r"./Images/육성을_끝낸_우마무스메는_일정_기준으로_평가받은_후.png")
최고_랭크를_목표로_힘내세요 = imreadUnicode(r"./Images/최고_랭크를_목표로_힘내세요.png")
랭크_육성 = imreadUnicode(r"./Images/랭크_육성.png")
육성을_끝낸_우마무스메는_인자를 = imreadUnicode(r"./Images/육성을_끝낸_우마무스메는_인자를.png")
계승_우마무스메로_선택하면_새로운_우마무스메에게 = imreadUnicode(r"./Images/계승_우마무스메로_선택하면_새로운_우마무스메에게.png")
인자획득 = imreadUnicode(r"./Images/인자획득.png")
우마무스메_상세_닫기_화살표 = imreadUnicode(r"./Images/우마무스메_상세_닫기_화살표.png")
평가점 = imreadUnicode(r"./Images/평가점.png")
보상획득 = imreadUnicode(r"./Images/보상획득.png")
강화_편성_화살표 = imreadUnicode(r"./Images/강화_편성_화살표.png")
레이스_화살표 = imreadUnicode(r"./Images/레이스_화살표.png")
팀_경기장_화살표 = imreadUnicode(r"./Images/팀_경기장_화살표.png")
오리지널_팀을_결성_상위_CLASS를_노려라 = imreadUnicode(r"./Images/오리지널_팀을_결성_상위_CLASS를_노려라.png")
하이스코어를_기록해서_CLASS_승급을_노리자 = imreadUnicode(r"./Images/하이스코어를_기록해서_CLASS_승급을_노리자.png")
기간_중에_개최되는_5개의_레이스에 = imreadUnicode(r"./Images/기간_중에_개최되는_5개의_레이스에.png")
서포트_카드의_Lv을_UP해서 = imreadUnicode(r"./Images/서포트_카드의_Lv을_UP해서.png")
팀_편성 = imreadUnicode(r"./Images/팀_편성.png")
전당_입성_우마무스메로_자신만의_팀을_결성 = imreadUnicode(r"./Images/전당_입성_우마무스메로_자신만의_팀을_결성.png")
팀_랭크를_올려서_최강의_팀이_되자 = imreadUnicode(r"./Images/팀_랭크를_올려서_최강의_팀이_되자.png")
팀_평가를_높이는_것이_팀_경기장을_공략하는_열쇠 = imreadUnicode(r"./Images/팀_평가를_높이는_것이_팀_경기장을_공략하는_열쇠.png")
팀_편성_다이와_스칼렛_화살표_클릭 = imreadUnicode(r"./Images/팀_편성_다이와_스칼렛_화살표_클릭.png")
출전_우마무스메_선택_다이와_스칼렛_화살표 = imreadUnicode(r"./Images/출전_우마무스메_선택_다이와_스칼렛_화살표.png")
팀_편성_확정_화살표 = imreadUnicode(r"./Images/팀_편성_확정_화살표.png")
편성을_확정합니다_진행하시겠습니까 = imreadUnicode(r"./Images/편성을_확정합니다_진행하시겠습니까.png")
팀_최고_평가점_갱신_닫기 = imreadUnicode(r"./Images/팀_최고_평가점_갱신_닫기.png")
홈_화살표 = imreadUnicode(r"./Images/홈_화살표.png")
공지사항_X = imreadUnicode(r"./Images/공지사항_X.png")
메인_스토리가_해방되었습니다 = imreadUnicode(r"./Images/메인_스토리가_해방되었습니다.png")
여러_스토리를_해방할_수_있게_되었습니다 = imreadUnicode(r"./Images/여러_스토리를_해방할_수_있게_되었습니다.png")


# 가챠
선물_이동 = imreadUnicode(r"./Images/선물_이동.png")
선물_일괄_수령 = imreadUnicode(r"./Images/선물_일괄_수령.png")
상기의_선물을_수령했습니다 = imreadUnicode(r"./Images/상기의_선물을_수령했습니다.png")
받을_수_있는_선물이_없습니다 = imreadUnicode(r"./Images/받을_수_있는_선물이_없습니다.png")
뽑기_이동 = imreadUnicode(r"./Images/뽑기_이동.png")
프리티_더비_뽑기 = imreadUnicode(r"./Images/프리티_더비_뽑기.png")
서포트_카드_뽑기 = imreadUnicode(r"./Images/서포트_카드_뽑기.png")
무료_쥬얼부터_먼저_사용됩니다 = imreadUnicode(r"./Images/무료_쥬얼부터_먼저_사용됩니다.png")
뽑기_결과 = imreadUnicode(r"./Images/뽑기_결과.png")
한_번_더_뽑기 = imreadUnicode(r"./Images/한_번_더_뽑기.png")
쥬얼이_부족합니다 = imreadUnicode(r"./Images/쥬얼이_부족합니다.png")
숫자3성_확정 = imreadUnicode(r"./Images/숫자3성_확정.png")
SSR_확정_스타트_대시 = imreadUnicode(r"./Images/SSR_확정_스타트_대시.png")
SSR_확정_메이크_데뷔_뽑기 = imreadUnicode(r"./Images/SSR_확정_메이크_데뷔_뽑기.png")
SSR_확정_메이크_데뷔_티켓을_1장_사용해 = imreadUnicode(r"./Images/SSR_확정_메이크_데뷔_티켓을_1장_사용해.png")
뽑기_결과_OK = imreadUnicode(r"./Images/뽑기_결과_OK.png")
상점_화면을_표시할_수_없습니다 = imreadUnicode(r"./Images/상점_화면을_표시할_수_없습니다.png")


# 연동하기
메뉴 = imreadUnicode(r"./Images/메뉴.png")
메뉴_단축 = imreadUnicode(r"./Images/메뉴_단축.png")
계정_정보 = imreadUnicode(r"./Images/계정_정보.png")
카카오_로그인 = imreadUnicode(r"./Images/카카오_로그인.png")
확인하고_계속하기 = imreadUnicode(r"./Images/확인하고_계속하기.png")
확인하고_계속하기2 = imreadUnicode(r"./Images/확인하고_계속하기2.png")
확인하고_계속하기3 = imreadUnicode(r"./Images/확인하고_계속하기3.png")
계속하기 = imreadUnicode(r"./Images/계속하기.png")
정보_확인_중 = imreadUnicode(r"./Images/정보_확인_중.png")
Google_계정으로_로그인 = imreadUnicode(r"./Images/Google_계정으로_로그인.png")
인증되지_않는_로그인_방법_입니다 = imreadUnicode(r"./Images/인증되지_않는_로그인_방법_입니다.png")
카카오_로그인_연동에_성공하였습니다 = imreadUnicode(r"./Images/카카오_로그인_연동에_성공하였습니다.png")
카카오_로그인_연동에_실패하였습니다 = imreadUnicode(r"./Images/카카오_로그인_연동에_실패하였습니다.png")
로그아웃 = imreadUnicode(r"./Images/로그아웃.png")


# 초기화
모두_지우기 = imreadUnicode(r"./Images/모두_지우기.png")
크롬_실행 = imreadUnicode(r"./Images/크롬_실행.png")
크롬_실행2 = imreadUnicode(r"./Images/크롬_실행2.png")
파이어폭스_실행 = imreadUnicode(r"./Images/파이어폭스_실행.png")
파이어폭스_연결된_서비스_관리 = imreadUnicode(r"./Images/파이어폭스_연결된_서비스_관리.png")
파이어폭스_문제_닫기 = imreadUnicode(r"./Images/파이어폭스_문제_닫기.png")
연결된_서비스_관리 = imreadUnicode(r"./Images/연결된_서비스_관리.png")
우마무스메_서비스 = imreadUnicode(r"./Images/우마무스메_서비스.png")
모든_정보_삭제 = imreadUnicode(r"./Images/모든_정보_삭제.png")
이_서비스의_모든_정보를_삭제하시겠습니까 = imreadUnicode(r"./Images/이_서비스의_모든_정보를_삭제하시겠습니까.png")
이_서비스의_모든_정보를_삭제하시겠습니까2 = imreadUnicode(r"./Images/이_서비스의_모든_정보를_삭제하시겠습니까2.png")
모든_정보_삭제_빨간_박스 = imreadUnicode(r"./Images/모든_정보_삭제_빨간_박스.png")
비밀번호 = imreadUnicode(r"./Images/비밀번호.png")
회원님의_소중한_정보_보호를_위해 = imreadUnicode(r"./Images/회원님의_소중한_정보_보호를_위해.png")
제안된_로그인 = imreadUnicode(r"./Images/제안된_로그인.png")
자동완성_Continue = imreadUnicode(r"./Images/자동완성_Continue.png")
자동완성_계속 = imreadUnicode(r"./Images/자동완성_계속.png")
비밀번호_확인 = imreadUnicode(r"./Images/비밀번호_확인.png")
삭제_완료 = imreadUnicode(r"./Images/삭제_완료.png")
로딩 = imreadUnicode(r"./Images/로딩.png")
카카오메일_아이디_이메일_전화번호 = imreadUnicode(r"./Images/카카오메일_아이디_이메일_전화번호.png")
로그인 = imreadUnicode(r"./Images/로그인.png")


# 특수 이벤트
튜토리얼을_스킵하시겠습니까 = imreadUnicode(r"./Images/튜토리얼을_스킵하시겠습니까.png")
재시도 = imreadUnicode(r"./Images/재시도.png")
타이틀_화면으로 = imreadUnicode(r"./Images/타이틀_화면으로.png")
숫자2단계_인증 = imreadUnicode(r"./Images/숫자2단계_인증.png")
확인 = imreadUnicode(r"./Images/확인.png")
앱_닫기 = imreadUnicode(r"./Images/앱_닫기.png")
날짜가_변경됐습니다 = imreadUnicode(r"./Images/날짜가_변경됐습니다.png")
추가_데이터를_다운로드합니다 = imreadUnicode(r"./Images/추가_데이터를_다운로드합니다.png")
숫자4080_에러_코드 = imreadUnicode(r"./Images/숫자4080_에러_코드.png")






# Images
# import glob, os
# from OpenCV_imread import imreadUnicode

# path = './Images'
# Images = dict()

# for a in glob.glob(os.path.join(path, '*')):
#     key = a.replace('.', '/').replace('\\', '/')
#     key = key.split('/')
#     Images[key[-2]] = imreadUnicode(a)


# if __name__ == "__main__":
#     for i in Images.keys():
#         print(i, end=", ")






# 서포트 카드
path = './Supporter_cards'
Supporter_cards = dict()

for a in glob.glob(os.path.join(path, '*')):
    key = a.replace('.', '/').replace('\\', '/')
    key = key.split('/')
    Supporter_cards[key[-2]] = imreadUnicode(a)

# SR_스윕_토쇼 = imreadUnicode(r"./Supporter_cards/SR_스윕_토쇼.png")
# SSR_골드_쉽 = imreadUnicode(r"./Supporter_cards/SSR_골드_쉽.png")
# SSR_골드_시티 = imreadUnicode(r"./Supporter_cards/SSR_골드_시티.png")
# SSR_그래스_원더 = imreadUnicode(r"./Supporter_cards/SSR_그래스_원더.png")
# SSR_니시노_플라워 = imreadUnicode(r"./Supporter_cards/SSR_니시노_플라워.png")
# SSR_보드카 = imreadUnicode(r"./Supporter_cards/SSR_보드카.png")
# SSR_비코_페가수스 = imreadUnicode(r"./Supporter_cards/SSR_비코_페가수스.png")
# SSR_사일런스_스즈카 = imreadUnicode(r"./Supporter_cards/SSR_사일런스_스즈카.png")
# SSR_사쿠라_바쿠신_오 = imreadUnicode(r"./Supporter_cards/SSR_사쿠라_바쿠신_오.png")
# SSR_세이운_스카이 = imreadUnicode(r"./Supporter_cards/SSR_세이운_스카이.png")
# SSR_슈퍼_크릭 = imreadUnicode(r"./Supporter_cards/SSR_슈퍼_크릭.png")
# SSR_스마트_팔콘 = imreadUnicode(r"./Supporter_cards/SSR_스마트_팔콘.png")
# SSR_스페셜_위크 = imreadUnicode(r"./Supporter_cards/SSR_스페셜_위크.png")
# SSR_아이네스_후진 = imreadUnicode(r"./Supporter_cards/SSR_아이네스_후진.png")
# SSR_에어_샤커 = imreadUnicode(r"./Supporter_cards/SSR_에어_샤커.png")
# SSR_엘_콘도르_파사 = imreadUnicode(r"./Supporter_cards/SSR_엘_콘도르_파사.png")
# SSR_오구리_캡 = imreadUnicode(r"./Supporter_cards/SSR_오구리_캡.png")
# SSR_위닝_티켓 = imreadUnicode(r"./Supporter_cards/SSR_위닝_티켓.png")
# SSR_타마모_크로스 = imreadUnicode(r"./Supporter_cards/SSR_타마모_크로스.png")
# SSR_토카이_테이오 = imreadUnicode(r"./Supporter_cards/SSR_토카이_테이오.png")
# SSR_트윈_터보 = imreadUnicode(r"./Supporter_cards/SSR_트윈_터보.png")
# SSR_파인_모션 = imreadUnicode(r"./Supporter_cards/SSR_파인_모션.png")
# SSR_하야카와_타즈나 = imreadUnicode(r"./Supporter_cards/SSR_하야카와_타즈나.png")