-- 뽑힌 캐릭터 8초 간격으로 출력
Print("------------------------------")
Print("엘 콘도르 파사 " .. pasa .. "장")
Print("골드 시티 " .. city .. "장")
Print("파인 모션 " .. motion .. "장")
Print("비코 페가수스 " .. pegasus .. "장")
Print("사쿠라 바쿠신 오 " .. bakushin .. "장")
Print("스페셜 위크 " .. week .. "장")
Print("아이네스 후진 " .. fujin .. "장")
Print("하야카와 타즈나 " .. tazuna .. "장")
Print("타마노 크로스 " .. cross .. "장")
Print("사일런스 스즈카 " .. suzuka .. "장")
Print("슈퍼 크릭 " .. creek .. "장")
Print("세이운 스카이 " .. sky .. "장")
Print("토카이 테이오 " .. teio .. "장")
Print("스마트 팔콘 " .. falcon .. "장")
Print("에어 샤커 " .. shakur .. "장")
Print("골드 쉽 " .. ship .. "장")
Print("니시노 플라워 " .. flower .. "장")
Print("그래스 원더 " .. wonder .. "장")
Print("위닝 티켓 " .. ticket .. "장")
Print("보드카 " .. vodka .. "장")
Print("오구리 캡 " .. cap  .. "장")
Print("------------------------------")
Print("총 SSR 합 " .. SSR_count .. "장")
Print("------------------------------")